### ISSUE TITLE
Add dynamic delete and cancel buttons

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#10]
When a user selects items from the todo or grocery list, two buttons should appear: Delete and Cancel. 
- Cancel should remove the checkmarks from the boxes and reset their status back to unchecked
- Delete should submit the form so the back-end can remove the checked items from the database

There are two forms here. One for the todos and one for the grocery list. Make sure the buttons appear for the correct list. If I check items for the todo list, then buttons should appear for the todo list.

**Comment by viggi-v** [comment]
Can I take this up

**Comment by MissMeg** [comment]
All yours!
