### ISSUE TITLE
Improve the design of the pop-up/modal windows

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#11]
When the plus symbol is clicked, a modal window is shown to the user where they can input information for either the grocery list or the todo list. The design of this window could be improved. Use the fonts and colors located under 'Main Styles' in the CSS file.

**Comment by MatheusMuriel** [comment]
Hi 😀, I can work on it. You can assign to me?

**Comment by MissMeg** [comment]
Take it away 👍

**Comment by Pranay0803** [comment]
@MissMeg I possible later I would also want to work on this

**Comment by MissMeg** [comment]
@Pranay0803 this issue has already been taken

**Comment by MissMeg** [comment]
The design is fine, it matches the general design, but it could be improved. This is open to interpretation and creativity.

**Comment by MatheusMuriel** [comment]
@MissMeg Ok! For optimization purposes, what is the resolution and screen size on which this application will be used?

**Comment by MissMeg** [comment]
Someone is currently working on making this responsive with #19 so currently, it is desktop-sized using a Macbook Pro's screen size but it will be updated for tablet and phone sizes too.
