### ISSUE TITLE
Delete items from the database

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#12]
Working with issue #10 

When the user selects items from their todo or grocery list to delete, the form will submit and these items will need to be deleted from the database. 

- add routes for both form submits to app.py
- inside of the route function, remove the items received from the form from the database (Pewee SQLlite database)
- redirect the user back to the homepage

**Comment by benji011** [comment]
Hi @MissMeg , can i take this please?

**Comment by MissMeg** [comment]
👍 all yours!
