### ISSUE TITLE
Align all checkboxes together

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#13]
Right now the checkboxes are a certain distance from the text on their line which makes them uneven and more difficult to check multiple items. 

Align the checkboxes so they are all aligned vertically together and the length of the text does not affect their placement.

This will need to work with issue #9

**Comment by icodechiranjib** [comment]
I would like to work on it!

**Comment by MissMeg** [comment]
🥳 It's yours!

**Comment by icodechiranjib** [comment]
I am not able to install the dependencies after creating the env. Can you help me out?

**Comment by Pranay0803** [comment]
@MissMeg I would like to work on this issue

**Comment by MissMeg** [comment]
@icodechiranjib were you able to get it working? 

If not, here's a great [guide on pipenv](https://realpython.com/pipenv-guide/)
There's also [directions in the readme](https://github.com/MissMeg/home-automation-app#running-the-project)

Let me know where you're stuck:
- What have you done so far? 
- Where did you get stuck?

**Comment by MissMeg** [comment]
@Pranay0803 this issue has already been taken

**Comment by icodechiranjib** [comment]
@MissMeg I am working on it.

**Comment by icodechiranjib** [comment]
I get error while running the app.py shows something like cannot import some module?
