### ISSUE TITLE
Add weather items to HTML using Flask templating

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#14]
Right now the weather data is just held at the bottom of the HTMl file. They need to be placed in the correct spot towards the top of the page inside of the weather section using Flask templating. 

Example of the data:
```python
({'temp': 87.7, 'weather': 'windy', 'wind': '5mph'}, {'temp': 84.3, 'weather': 'sunny'}, {'temp': 84.3, 'weather': 'sunny'}, {'temp': 84.3, 'weather': 'sunny'})
```

The first item being today's info, then tomorrow's, etc.

**Comment by hur** [comment]
Hey, I'd like to work on this.

**Comment by MissMeg** [comment]
Take it away 👍

**Comment by Allcatraz9** [comment]
I would like to work on this

**Comment by hur** [comment]
> I would like to work on this

I'm working on this, I have a PR ready soon.
