### ISSUE TITLE
Add a scheduler

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#16]
Right now the app only shows the date and weather info for the day the it has been run. If the app is left open, the weather and date at the top of the screen will need to be updated. 

- Install a scheduler - [Here's the one I would choose](https://pypi.org/project/schedule/) - Make sure it is added to the pipfile
- Schedule the weather to be run every 24hrs at 1am
- Schedule the date to be updated every 24hrs at 1am
- Test and make sure the scheduling works

**Comment by CodeSadhu** [comment]
@MissMeg  Would like to take this. Can you please assign it to me?

**Comment by MissMeg** [comment]
Sure thing!

**Comment by CodeSadhu** [comment]
@MissMeg Is there an hourly deadline before the assignee is switched? Sorry for the newb question btw, I'm a first time contributor...

**Comment by MissMeg** [comment]
I am not sure I understand your question @CodeSadhu.
If the app is left running, when it hits 1am of the next day, the date and weather should be updated to reflect the change in day. This should continue to happen every day at 1am if the app is left running. So if I run the app today and leave it running when it hits 1am tomorrow, the date should change to October 1st and the weather should update to show October 1st's temp, weather, wind speed, etc. Does that help?

**Comment by CodeSadhu** [comment]
@MissMeg Actually my question was a bit different. But I found the answer, so kindly ignore that... I'm going to start working on this right now.

**Comment by CodeSadhu** [comment]
@MissMeg Hey. This is my first time with a flask project. Should I just write the scheduler in the root or make a separate folder for it?

**Comment by benji011** [comment]
@CodeSadhu Command arguments is the wrong way round. Run this instead and it'll work 👍 

```bash
pipenv run python app.py
```

**Comment by CodeSadhu** [comment]
@benji011 Ahh damn lol. Thanks! 😄

**Comment by lpedrop** [comment]
@MissMeg

By doing it like that, a scheduler to run at 1am, you will face one problem that it will be dependent on the location where it will be hosted and not related to the location of the user (US vs EU, or EAST vs WEST mess).
Another problem is that, on the calendar, appoitments added and removed to Google Calendar during the running day, or weather changes, will not be reflected until the next scheduler refresh.

Why not doing it in one of this two ways:
- add a refresh button that allows the user to refresh the page on request (if the app is running on maximized tab/browser)
or
- add the meta tag 'refresh' to the head of the HTML and the page will refresh itself after the desired elapsed minutes or seconds
