### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#2]
*Please read the [contribution guide](https://github.com/MissMeg/home-automation-app/blob/master/Contributing.md) before claiming an issue.*

*[Videos from my livestreams of this project](https://www.youtube.com/playlist?list=PLuC2HflhhpLGQinrUz8j6c2eSzzZ0EsfH)*

### Issues open for claiming:
*I've run out of ideas for issues 😂   but feel free to add one of your own! Review the videos above to see the app for inspiration.*

### Issues claimed:
- Checkbox alignment #9 
- Adding cancel and delete buttons #10 
- Improve design of modals #11 
- Align checkboxes together #13
- Add weather items to HTML #14 
- Add a scheduler #16
- Blank slate #17 
- Reduce calendar card size #18 
- Mobile friendly #19 
- Themes and light/dark #30 

### Issues completed:
- Docker #3 
- #6  
- Add routes for removing items from the database #12 
- Animations and interactions #20

**Comment by benji011** [comment]
Hi, I'm interested in contributing for Hacktoberfest!

**Comment by MissMeg** [comment]
Hi @benji011 ! Glad to hear it! I'll be talking about the issues for this project and how to contribute during my livestream on September 21st. You can catch it [here](https://www.twitch.tv/team_treehouse). Otherwise, be on the lookout for the issues to start popping up after that stream.  I also have the [contribution guide](https://github.com/MissMeg/home-automation-app/blob/master/Contributing.md) ready as well.

**Comment by beingaryan** [comment]
Hey MissMeg! I'm also interested in contributing for Hacktoberfest! How to attend the Live Webinars for the same where you'll be revealing the procedures for contributions?

**Comment by MissMeg** [comment]
Hi @beingaryan ! The livestream will be live on Twitch [here](https://www.twitch.tv/team_treehouse) at 2pm CST on September 21st. I will walk through the process for contributing with an example issue and talk through some of the issues that will be available. The video will stay up on Twitch if you are unable to make the livestream so you can still get the info 😄

**Comment by Zubair-12** [comment]
Hi @MissMeg I am a beginner. I want to contribute in this. Can I?

**Comment by benji011** [comment]
Hi @MissMeg I checked the Twitch link for the livestream but seems the video isn't up. Was it today that you were going to go live or is it actually tonight?

**Comment by MissMeg** [comment]
@Zubair-12  definitely!

@benji011  it’s tomorrow. Sept 21st at 2pm CST 👍

**Comment by keivalya** [comment]
I'm a beginner to Open-source as well as HacktoberFest and will be glad if I could help :)

**Comment by MissMeg** [comment]
@keivalya welcome! I'll be posting the issues up for grab on Sept 30th 👍

**Comment by knowyours** [comment]
Hello! I am complete beginner to open source activities. Can you please help me get started? @MissMeg

**Comment by zippytyro** [comment]
I would love to contribute

**Comment by claire-me** [comment]
I'll also love to contribute @MissMeg

**Comment by MissMeg** [comment]
@knowyours @zippytyro @claire-me Hi, all! Welcome! 
I've detailed out how to contribute with the [contribution guide](https://github.com/MissMeg/home-automation-app/blob/master/Contributing.md). You can also see me walk through an example of how this process works in [this video](https://www.twitch.tv/videos/747992514) from our livestream last week.

I am posting the issues up for grabs tomorrow, Sept 30th. Topics will be mostly in Python (Flask), CSS, and JavaScript (Front-End).

**Comment by nithin0905** [comment]
Hi, I'm interested in contributing to this project! And I'm kind of a newbie so just getting my hands on.

**Comment by MissMeg** [comment]
#### Update
I have added all of the issues I thought of for bugs and features. You can still check out the project and suggest any features or ideas you have for improvements. You can also look for typos to fix as well. I know someone found a typo in the readme already #25
