### ISSUE TITLE
Animations and interactions

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#20]
Use CSS and front-end JavaScript to add engaging animations and interactions across the app. Have fun with it! Animations and interactions should not distract from the app only enhance the experience.

**Comment by Capt-Titanium** [comment]
Heyy! can I work on this issue?

**Comment by MissMeg** [comment]
Go for it 👍

**Comment by Pranay0803** [comment]
I would also like to work on this one

**Comment by MissMeg** [comment]
@Pranay0803 this issue has already been claimed

**Comment by Capt-Titanium** [comment]
I have added  some animations to the project. However, there are some merge conflicts. I hope you can help out with it.
Please check PR #33 . Also shortly, I will be submitting the PR for mobile view of index.html. Hope you like the animations :)
