### ISSUE TITLE
Containerize the app into Docker

### ISSUE THREAD

**Issue by benji011** [MissMeg/home-automation-app#3]
## Why

It took me a good few minutes to set up the project locally. And i remembered everyones local machine is different so using Docker would improve set up time by a lot.

## What

1. Create set up files
2. Containerize app
3. Update `README.md` on how to build & run app
3. Update `README.md` on where to store your key files securely (locally)

@MissMeg If it's ok, I'd like to give this a go, assign myself & make 4 PRs during Hacktoberfest on the above things. Is this ok?

**Comment by MissMeg** [comment]
Hi @benji011 ! I think that sounds great, though I am not familiar with Docker. Can you explain a bit more about how it would help?

**Comment by MissMeg** [comment]
Thanks @benji011 !

A couple questions came up after watching the video:

- Would individuals wanting to run this project then need to have a docker account?
- How would the private keys in the keys.py file work? (Google cal auth code, weather API key) Will each individual still be able to set their own keys to get their calendar and weather information?

**Comment by benji011** [comment]
@MissMeg 
> Would individuals wanting to run this project then need to have a docker account?

Nah. You just download the software, continue through the prompted instructions and it runs as a daemon on your machine. With the daemon running we can use the docker commands to set up then run the project app.

> How would the private keys in the keys.py file work? (Google cal auth code, weather API key) Will each individual still be able to set their own keys to get their calendar and weather information?

When i installed and set up this project, I noticed that `keys.py` was excluded in `.gitignore`. But we don't need to do this if we can load using environment variables. I configure using the command in bash like:

```bash
export WEATHER_KEY="<my_api_weather_key>"
```

This assigns my API key to `WEATHER_KEY` locally.

My `keys.py` file now looks like this:

```python3
import os

weather_key = os.environ['WEATHER_KEY']
# ...
```
Where `os.environ['WEATHER_KEY']` tells Python to look for an environment variable with the key `WEATHER_KEY`.
With this approach you don't need to worry about hard coding keys or ignoring this file.

We can specify with environment variables using Docker in the settings file (reference [here](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)). Although I'd need to update the README to explain how we can do that here.

I think with this approach, we save time for set up and make the app secure also :)

**Comment by MissMeg** [comment]
Ah ok, so you would still need the keys.py file with either environment variables or regular variables depending on how you setup the settings file and readme to explain 👍 I just wanted to make sure one person's keys we not being used when others ran the program so they can customize it to their calendar and list items. 😉 

I'd definitely go with whichever is easier to explain. It may be easier to keep regular variables inside of a keys.py file so you are not trying to explain both how to install and use with docker *and* how to create env variables, but I am down for you to try if you are up for it! 😄 

I think it sounds good to me 👍
