### ISSUE TITLE
Add the 'hacktoberfest' topic to repo

### ISSUE THREAD

**Issue by benji011** [MissMeg/home-automation-app#32]
@MissMeg it seems PRs in this repo (after 3rd Oct UTC) will now only count towards the event if the topic is set to `hacktoberfest`

ref: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Capt-Titanium** [comment]
@MissMeg please fix this as we really need the PRs made here to be counted as genuine towards hacktober fest
