### ISSUE TITLE
Refactor 'gcalendar.py' a bit

### ISSUE THREAD

**Issue by benji011** [MissMeg/home-automation-app#7]
## Why

I'd like to contribute to refactoring some of the code in this file & rename a few things. What do you think @MissMeg ? If this is ok, I can do this pretty quickly (but i'll work on dockerizing the app first)

**Comment by MissMeg** [comment]
👋 I left the code in this file, besides my small additions, to match the code from [Google's docs](https://developers.google.com/calendar/quickstart/python) so it can be easily matched for those learning. I would like it to stay matching. If you're refactoring my small method at the end, then go for it.
