### ISSUE TITLE
Checkbox misaligned when checked

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/home-automation-app#9]
When the checkbox is checked, it drops out of alignment and the checkmark in the box doesn't show.

- Make sure the box stays in its current location when checked
- Make sure the checkmark appears inside the box when it is checked

**Comment by claire-me** [comment]
Hey @MissMeg would love to take this.

**Comment by MissMeg** [comment]
Take it away! 😄

**Comment by claire-me** [comment]
Hey @MissMeg Please where is the codebase that needs this change
